### ISSUE TITLE
IDEA: Add Current Chunk Indicator

### ISSUE THREAD

**Issue by aaj6fm** [XrioBtw/world-location#2]
Consider adding a field in the config panel or on the tooltip to state what chunk you are standing in / hovering over with your mouse. Currently the only way to determine chunks for non-world map locations such as the burthorpe games room basement is to use dev tools (location).

**Comment by XrioBtw** [comment]
Sorry for the late response.
This has now been addressed, and the plugin has been updated. See [plugin-hub update #1722](https://github.com/runelite/plugin-hub/pull/1722) for more information.
Please let me know if there are other changes you would like to see.
