### ISSUE TITLE
Grid Info Region ID incorrect for Molly Random Event Instance

### ISSUE THREAD

**Issue by aaj6fm** [XrioBtw/world-location#3]
Location: Molly Random Event

Correct Region ID for Molly Random event is 7504 as indicated by dev tools. Grid info displayed a different region id every time I logged out and logged back in (receiving a new instance).

Thanks for adding this feature to the plugin. It's working great everywhere else!

World Location 1:

![runelite-world-location2](https://user-images.githubusercontent.com/7975992/128195537-e4f33706-cb2f-4fce-bede-273ea8df911f.PNG)

Dev Tools:

![runelite-devtools](https://user-images.githubusercontent.com/7975992/128195542-2eb7bf0e-c5c1-45cb-b6b4-ca5c79650086.PNG)

World Location 2:

![runelite-world-location](https://user-images.githubusercontent.com/7975992/128195543-2f2e960b-e951-4df9-a895-79d4015ffd26.PNG)

**Comment by XrioBtw** [comment]
Thank you for pointing this out!

Although I was aware that instances place you into new coordinates on login, it seems there are more to these IDs than I had anticipated. I have only combined the player tile X & Y coordinates into a unique integer, but for instances the DevTool displays the instance template region ID and not the one you are really inside. I highly recommend that you check out [the map Mejrs made for the OSRS Wiki](https://mejrs.github.io/osrs?m=-1&z=2&p=0&x=1888&y=5151&layer=grid) if you don't know about this one already. That map was the inspiration for me to add the config option `Grid Info Type` with the `Local coordinates` option, and this is the format Jagex is using behind the scenes (a format that makes a lot more sense than the ridiculous and probably useless chunk IDs that my plugin can display).

I will likely fix your issue soon, either with a toggleable config option or displaying the instance template ID alongside the current one.

Finally, what information from my plugin or the DevTools is or could be useful for you? Is it the instance template or instance copy that is interesting/useful for you, or maybe both? Personally I only really use the (X, Y, Z) world location and the region displayed as (i, j, x, y) local coordinates, so I was slightly surprised to see that the region ID was of interest to you.

**Comment by aaj6fm** [comment]
I'm playing a chunkman ironman, youtube examples are slay brother's chunkus lad, pookaguy's one chunk at a time ...etc.

We region lock our account to unlocking one chunk (in this case region) at a time. You can see chunk pickers here:

https://source-chunk.github.io/chunk-picker-rs3/?ujt

https://source-chunk.github.io/chunk-picker-v2/?fft

Those pickers work great but do not allow me to unlock dungeons / instances one chunk at a time (I prefer it and it feels more chunky). I use the [Region Locker](https://github.com/slaytostay/region-locker) runelite plugin for osrs. In it I can specify these unique region ids and the plugin offers a nice shader to let me know which chunks are unlocked and which aren't. Before your grid info update, the only way I could get underground chunks was with dev tools. now its much more convenient to use your plugin.

For your plugin, the instance template region id is really what I'm looking for. I've been in multiple other random events with presumable instances and your current version is working fine.

**Comment by XrioBtw** [comment]
The plugin has now been [updated](https://github.com/runelite/plugin-hub/pull/1745).
I added a new config `Instance Info Type` to determine how to handle coordinates and IDs inside instances.
![image](https://user-images.githubusercontent.com/33559295/128598061-ae3002de-561b-46ae-bf08-103dc2c0ab70.png)
You can just leave this setting at `Template`.
